language: cpp

os:
 - linux
 - osx

compiler:
 - clang
 - gcc

before_script:
 - git clone https://github.com/Itseez/opencv.git
 - cd opencv
 - git checkout 2.4
 - mkdir build
 - cd build
 - cmake ..
 - make -j4
 - sudo make -j4 install
 - cd ../..
 - mkdir build
 - cd build
 - cmake ..

script: make

