language: cpp

os:
 - linux
 - osx

compiler:
 - clang
 - gcc

before_script:
#OpenCV
 - git clone https://github.com/Itseez/opencv.git
 - cd opencv
 - git checkout 2.4
 - mkdir build
 - cd build
 - cmake ..
 - make -j4
 - sudo make -j4 install
 - cd ../..
#Google Log
 - svn checkout http://google-glog.googlecode.com/svn/trunk/ glog
 - cd glog
 - ./configure
 - make -j4
 - sudo make -j4 install
 - cd ..
#Google Test
 - svn checkout http://googletest.googlecode.com/svn/trunk/ gtest
 - cd gtest
 - mkdir build
 - cd build
 - cmake ..
 - make
 - make vtest
 - sudo make install
 - cd ../..
#Main Program
 - mkdir build
 - cd build
 - cmake ..

script: make

