language: cpp

os:
 - linux
 - osx

compiler:
 - clang
 - gcc

before_install:
 - sudo add-apt-repository --yes "deb http://ppa.launchpad.net/boost-latest/ppa/ubuntu precise main"
 - sudo add-apt-repossitory --yes "deb-src http://ppa.launchpad.net/boost-latest/ppa/ubuntu precise main"
 - sudo apt-get update

install:
#Upgrade
# - sudo apt-get --yes --force-yes upgrade
#Boost
 - sudo apt-get install libboost-all-dev libboost-random-dev
 - dpkg -s libboost-dev | grep 'Version'
#Google Log
 - svn checkout http://google-glog.googlecode.com/svn/trunk/ glog
 - cd glog
 - ./configure
 - make -j4
 - sudo make -j4 install
 - cd ..
#Google Test
 - sudo apt-get install libgtest-dev
 - mkdir gtest
 - cd gtest
 - cmake /usr/src/gtest/
 - make
 - sudo mv libg* /usr/lib/
 - cd ..
#OpenCV
 - git clone https://github.com/Itseez/opencv.git
 - cd opencv
 - git checkout 2.4
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_java=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF ..
 - make -j4
 - sudo make -j4 install
 - cd ../..


before_script:
#Main Program
 - mkdir build
 - cd build
 - cmake ..

script: make

